In [1]:
import numpy as np

In [3]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
m1 = np.array([[1, 2, 3], [4, 5, 6]])
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
r1 = np.arange(0, 10, 2)
r1

array([0, 2, 4, 6, 8])

In [12]:
l1 = np.linspace(0, 10, 11) # in 11 elements from 0 to 10
l1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])